### ISSUE TITLE
knife supermarket didn't use chefignore file

### ISSUE THREAD

**Issue by kaltokri** [chef/knife-supermarket#19]
I've added a standard chefignore file to our cookbooks. It includes a lot of default entries like this:

```
.vagrant
Vagrantfile
```

But when I call knife supermarket share ... the Vagrantfile is added to the cookbook tar.gz file.

**Comment by mcallb** [comment]
This is a bug https://github.com/chef/chef/issues/2994. We work around the issue by copying the chefignore file up one directory to our cookbook_path.

**Comment by nellshamrell** [comment]
Closing, since we are aware and tracking in [chef/chef#2994](https://github.com/chef/chef/issues/2994)
