### ISSUE TITLE
Need way to specify collaborators on a cookbook

### ISSUE THREAD

**Issue by SolverDude** [chef/knife-supermarket#25]
As presently working, the person invoking 'knife supermarket share' is the ONLY person who can maintain that cookbook in supermarket.

This model seems a little goofy to me.  If i'm an admin as defined in supermarket, i'd expect to be able to maintain ANY cookbook in the supermarket.

Having a command line means to specify shared collaborators would alleviate this.  Perhaps a change to supermarket would also be in order.

**Comment by robbkidd** [comment]
Hi, @solverdude. Thanks for the feedback.

Administrative rights on a Supermarket is a separate privilege concern from collaborating on a cookbook.

Supermarket has collaborators and collaborator groups for expanding the number of people who can perform maintenance tasks on a cookbook. Is this a request to add to `knife supermarket` commands to add/remove collaborators and collaborator groups to a cookbook? What would you picture that command looking like?

**Comment by nellshamrell** [comment]
@SolverDude, any thoughts on @robbkidd's comment above?

**Comment by SolverDude** [comment]
Sorry, on vacation.

If i add cookbooks via supermarket share, no one else can add a version of
them, without first going through supermarket gui and baking themselves
collabs.  I'd like an option to specify the collaborators in the share
command, and maybe one to change collaborators for an existing cookbook.

That's my initial thoughts.  Does that make sense?

**Comment by SolverDude** [comment]
@nellshamrell and @robbkidd , to further clarify [i'm back to work], I was expecting my being an admin in supermarket to be equivalent to being an admin in Chef Server.  But it isn't that model at present.  So my feature request was more to address the model supermarket uses, and to specify collaborators on adding a cookbook.

I think that the definition Chef server uses for admin is preferred, on further reflection.  Any admin could push any new cookbook version, in my fantasy world.  That might imply another role layer, like 'committer' or something, where they'd need to be a collaborator to add a version.  Then my above enhancement to knife supermarket would apply.

**Comment by lamont-granquist** [comment]
this is more of a bug against supermarket than knife-supermarket
