### ISSUE TITLE
knife supermarket {list,search,show} fails with undefined method "get_rest"

### ISSUE THREAD

**Issue by atombaby** [chef/knife-supermarket#27]
I have run into an issue with some of the `knife supermarket` subcommands, specifically list, search, and show.  This seems to coincide with a recent upgrade to chefdk 11.x

When I run any of those commands, I get the following:

```
$ knife supermarket list -VV
INFO: Using configuration from /home/foo/.chef/knife.rb
/home/foo/.chefdk/gem/ruby/2.1.0/gems/knife-supermarket-0.2.2/lib/chef/knife/supermarket_list.rb:40:in `get_cookbook_list': undefined method `get_rest' for #<Chef::HTTP::SimpleJSON:0x0000000296ed60> (NoMethodError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/cookbook_site_list.rb:39:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:416:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:415:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/knife.rb:148:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:50:in `load'
	from /opt/chefdk/bin/knife:50:in `<main>'
```

It looks like other commands (download, share) seem to work OK.  I notice that (apparently) from Chef 11 on, that the `get_rest` method has been changed to an alias.  Not sure if that's the reason it's failing, but when I changed `get_rest` to just plain `get` it works fine.

It's entirely possible I've got other issues, but I've been unable to figure out what those might be.  I did fork and I can put the changes into a pull request if you'd like to incorporate these.

Thanks much

**Comment by robbkidd** [comment]
Thanks for reporting, @atombaby ! 

A couple of Chefs have confirmed the behavior, too. We'll triage this next week for investigation.

Also reported to be a problem with ChefDK 0.10.0 (chef client 12.7.0).

**Comment by akemner** [comment]
we just hit this bug as well

**Comment by robbkidd** [comment]
Working this now!

**Comment by robbkidd** [comment]
Should be fixed now. New gem [version 0.2.3 up on RubyGems](https://rubygems.org/gems/knife-supermarket/versions/0.2.3).

**Comment by robbkidd** [comment]
OK. Really, really fixed now. New new [gem version 0.2.4 up on Rubygems](https://rubygems.org/gems/knife-supermarket/versions/0.2.4).
