### ISSUE TITLE
RakeTask for knife supermarket share

### ISSUE THREAD

**Issue by jsirex** [chef/knife-supermarket#30]

**Comment by robbkidd** [comment]
@jsirex Can you be more specific about your request or issue?

Is adding a rake task to your project's Rakefile like:

```

**Comment by jsirex** [comment]
I want to add rake tasks for knife goals.
Actually my global goal is: setup an release process for cookbooks with supermarket.

I'm using cookbook centric approach and supermarket. Currently there is no official way (plugins) to do that well. I found `stove` gem. There are also `Knife Community` and `Emeril` but they have its own disadvantages.

Having rake tasks for all knife part makes it possible to create an `rake publish` task, which will be smart and flexible.

**Comment by robbkidd** [comment]
The [delivery-truck cookbook](https://github.com/chef-cookbooks/delivery-truck) represents a pretty official release lifecycle for cookbooks. The recipes in that cookbook are the implementations for various phases of the development of a cookbook.

The `publish` recipe has actions for publishing to [a supermarket](https://github.com/chef-cookbooks/delivery-truck/blob/master/recipes/publish.rb#L73-L77) and a [chef server](https://github.com/chef-cookbooks/delivery-truck/blob/master/recipes/publish.rb#L109-L111), both of which are `execute` statements for `knife` commands. I recommend for your `publish` rake task to start by adding an execute statement for `knife supermarket share` with appropriate options for your environment.

**Comment by lamont-granquist** [comment]
out of scope for this repo
