### ISSUE TITLE
knife.rb settings not honored in windows

### ISSUE THREAD

**Issue by JackChance** [chef/knife-supermarket#32]
When I ran my `knife supermarket share foo -z -VV` command it would always show that it was looking for my cookbooks in c:/chef regardless of what my chef_repo_path and cookbook_path options were set to.

To get around this I moved my repository to c:/chef

**Comment by robbkidd** [comment]
We'll investigate! Thanks!

**Comment by robbkidd** [comment]
Maybe related to #15 ?

**Comment by nellshamrell** [comment]
Just confirmed that this works with explicitly defining the cookbook-path in the command line, i.e.

$ knife supermarket share test-cookbook --cookbook-path './some-directory'

Testing this with cookbook-path defined in the knife.rb

**Comment by nellshamrell** [comment]
I just tested this using Windows 7 and Chef DK 0.15.15

It worked with both with 

$ knife supermarket share test-cookbook --cookbook-path './some-directory'

And defining the cookbook-path in knife.rb like this:

knife[:cookbook_path] = 'path/to/some-directory'

@JackChance: could you let me know what version of Windows and what version of Chef DK you are using?

**Comment by nellshamrell** [comment]
@JackChance going to go ahead and close this as I have not been able to replicate this.  Feel free to re-open, though, if you see the issue again!
